name: test and lint
on: push
jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: install dependencies
        run: make install
      - name: run linter
        run: make lint
      - name: run tests
        run: make test
      - name: upload code coverage
        uses: ./.github/actions/cc-test-reporter
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          subcommand: "upload-coverage"
